# Site settings
title: Floris Jansen
description: >-
  Hej! Iâ€™m Floris, I design and develop for inclusion, accessibility, privacy and sustainability.
baseurl: "" # the subpath
url: "https://fmjansen.com"
github_username:  fmjansen

# Build settings
markdown: kramdown

# Collection
collections:
  posts:
    permalink: /:collection/:title/
    output: true

webmention:
  username: "fmjansen.com"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - gulpfile.js
  - package-lock.json
  - package.json
  - src
